- name: install desktop base packages
  community.general.pacman:
    name: "{{ desktop_base_packages }}"
    update_cache: true
  become: true

- name: install desktop aur packages
  aur:
    name: "{{ item }}"
    use: yay
    state: present
  loop: "{{ desktop_aur_packages }}"
