- name: install desktop base packages
  community.general.pacman:
    name: "{{ desktop_base_packages }}"
    update_cache: yes
  become: yes

- name: install desktop aur packages
  aur:
    name: "{{ item }}"
    use: yay
    state: present
  loop: "{{ desktop_aur_packages }}"
