- name: install provision packages
  community.general.pacman:
    name: "{{ provision_base_packages }}"
    update_cache: yes
  become: yes

- name: add aur_builder user
  ansible.builtin.user:
    name: aur_builder
    group: wheel
    create_home: yes
    home: /var/aur_builder/
  become: yes

- name: add aur_builder pacman access
  ansible.builtin.lineinfile:
    path: /etc/sudoers.d/60-aur_builder
    state: present
    line: 'aur_builder ALL=(ALL) NOPASSWD: /usr/bin/pacman'
    create: yes
    mode: 0600
    validate: 'visudo -cf %s'
  become: yes

- name: install yay
  aur:
    name: yay
    use: makepkg
    state: present
  become: yes
  become_user: aur_builder

- name: install i3blocks
  aur:
    name: i3blocks
    use: yay
    state: present
