---
- name: include os specific variables
  include_vars: "{{ ansible_distribution|lower }}-{{ ansible_distribution_version.split('.')[0]|lower }}.yml"

- name: copy user-dirs.dirs file
  ansible.builtin.copy:
    src: user-dirs.dirs
    dest: /tmp/user-dirs.dirs
    mode: 0644

- name: copy xdg bash script
  ansible.builtin.copy:
    src: xdg.sh
    dest: /tmp/xdg.sh
    mode: 0755

- name: execute xdg script
  ansible.builtin.command:
    cmd: /tmp/xdg.sh
    creates: /tmp/.xdg-provision

- name: archlinux
  include_tasks: archlinux.yml
  when: ansible_distribution|lower == "archlinux"

- name: ubuntu
  include_tasks: ubuntu.yml
  when: ansible_distribution|lower == "ubuntu"

- name: set timezone
  community.general.timezone:
    name: "{{ provision_timezone }}"
  become: yes

- name: get current locale and language configuration
  command: localectl status
  register: locale_status
  changed_when: false

- name: parse lanf from current locale and language configuration
  set_fact:
    locale_lang: "{{ locale_status.stdout | regex_search('LANG=([^\n]+)', '\\1') | first }}"
    locale_keymap: "{{ locale_status.stdout | regex_search('VC Keymap: ([^\n]+)', '\\1') | first }}"
    locale_layout: "{{ locale_status.stdout | regex_search('X11 Layout: ([^\n]+)', '\\1') | first }}"

- name: set locale
  ansible.builtin.command:
    cmd: "localectl set-locale LANG={{ provision_locale }}"
  changed_when: locale_lang != provision_locale
  become: yes

- name: set keyboard
  ansible.builtin.command:
    cmd: "localectl set-keymap --no-convert {{ provision_keymap }}"
  changed_when: locale_keymap != provision_keymap
  become: yes

- name: set x11 keyboard
  ansible.builtin.command:
    cmd: "localectl set-x11-keymap --no-convert {{ provision_keymap_x11 }}"
  changed_when: locale_layout != provision_keymap_x11
  become: yes

- name: set the gdm default session
  ansible.builtin.copy:
    dest: "/var/lib/AccountsService/users/{{ ansible_user_id }}"
    owner: root
    group: root
    mode: 0600
    force: no
    content: |
      [User]
      Language=
      Session=i3
      XSession=i3
  become: yes

- name: start gdm service
  ansible.builtin.service:
    name: gdm
    enabled: yes
  become: yes

- name: create various directories
  ansible.builtin.file:
    path: "{{ item }}"
    owner: "{{ ansible_user_id }}"
    group: "{{ ansible_user_id }}"
    mode: 0755
    state: directory
  loop:
    - $HOME/.cloud
    - $HOME/bin
    - $HOME/tmp
    - $HOME/.fonts
    - $HOME/.icons
    - $HOME/.vim
    - $HOME/.vim/autoload

- name: clone dotfiles
  ansible.builtin.git:
    repo: "{{ provision_dotfiles_repo }}"
    dest: $HOME/.dotfiles
    force: yes
    update: no
    version: master

- name: vim plug
  ansible.builtin.get_url:
    dest: ~/.vim/autoload/plug.vim
    url: https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
    owner: "{{ ansible_user_id }}"
    group: "{{ ansible_user_id }}"
    mode: 0644
